version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aidas-portfolio
    restart: always
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    networks:
      - caddy_caddy_network

networks:
  caddy_caddy_network:
    external: true
 