name: Build and Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H linux-namai.giize.com >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: |
          rsync -av --delete \
            --exclude 'node_modules/' \
            --exclude 'dist/' \
            --exclude 'logs/' \
            --exclude 'trash/' \
            --exclude '.git/' \
            --exclude '.env.local' \
            -e "ssh -i ~/.ssh/id_rsa" \
            . aidas@linux-namai.giize.com:/home/aidas/Documents/resume/

      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa aidas@linux-namai.giize.com '
            cd /home/aidas/Documents/resume &&
            echo "Stopping existing containers..." &&
            docker compose down 2>/dev/null || true &&
            echo "Cleaning up Docker images..." &&
            docker image prune -af &&
            echo "Building new image..." &&
            docker compose build --no-cache &&
            echo "Starting containers..." &&
            docker compose up -d &&
            echo "Checking container status..." &&
            docker compose ps &&
            echo "Deployment completed!"
          '

      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/id_rsa aidas@linux-namai.giize.com '
            sleep 10 &&
            if docker compose -f /home/aidas/Documents/resume/docker-compose.yml ps | grep -q "Up"; then
              echo "✅ Deployment successful!"
            else
              echo "❌ Deployment failed!"
              docker compose -f /home/aidas/Documents/resume/docker-compose.yml logs
              exit 1
            fi
          '
